title: ioc Handbook
email: ioc@bsd.ci

permalink: pretty

chapters:
  -
    title: Getting Started
    chapters:
      -
        title: Dependencies
        url: /getting-started/dependencies/
      -
        title: Installation
        url: /getting-started/installation/
      -
        title: Global Configuration
        url: /getting-started/global-config/
      -
        title: The First Jail
        url: /getting-started/first-jail/
  -
    title: About ioc
    chapters:
      -
        title: Intro
        url: /about/intro/
      -
        title: Security Model
        url: /about/security-model/
      -
        title: Bug Reporting
        url: /about/bug-reporting/
      -
        title: Compatibility
        url: /about/compatibility/
      -
        title: Contributor Covenant Code of Conduct
        url: /about/code-of-conduct/
      -
        title: Migration
        url: /about/migration/
  -
    title: ioc Library Essentials
    chapters:
      -
        title: Release
        url: /library-essentials/release/
      -
        title: Jail
        url: /library-essentials/jail/
      -
        title: Releases and Jails
        url: /library-essentials/releases-and-jails/
      -
        title: Events and Generators
        url: /library-essentials/events-and-generators/
      -
        title: Errors
        url: /library-essentials/errors/
      -
        title: Logger
        url: /library-essentials/logger/
  -
    title: Features
    chapters:
      -
        title: Release Management
        url: /features/release-management/
      -
        title: Networking
        url: /features/networking/
      -
        title: Resource Filters
        url: /features/resource-filters/
      -
        title: Jail Config
        url: /features/jail-config/
      -
        title: Nested Jails
        url: /features/nested-jails/
      -
        title: Shared ZFS datasets
        url: /features/shared-zfs-datasets/
      -
        title: NullFS mounts
        url: /features/nullfs-mounts/
      -
        title: Resource Limits
        url: /features/resource-limits/
      -
        title: Packages
        url: /features/packages/
      -
        title: Hook Environment Variables
        url: /features/environment/
      -
        title: Provisioning
        url: /features/provisioning/
  # -
  #   title: Advanced Library Usage
  #   chapters:
  #     -
  #       title: Daemon
  #       url: /advanced/daemon/
  #     -
  #       title: REST-API
  #       url: /advanced/rest-api/
  #     -
  #       title: Logging
  #       url: /advanced/logging/
  #     -
  #       title: Ephemeral Jails
  #       url: /advanced/ephemeral-jails/
  #     -
  #       title: Green/Blue Development
  #       url: /advanced/green-blue-development/
  #     -
  #       title: Rolling Updates
  #       url: /advanced/rolling-updates/
  #     -
  #       title: Phoenix Deployment
  #       url: /advanced/phoenix-deployment/

ioc_cli_tool: "ioc"
current_fbsd_release: "11.2-RELEASE"

sass:
  style: compact
  sass_dir: css

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "handbook"
