title: iocage Handbook
email: authors@iocage.io

chapters:
  -
    title: Getting Started
    path: getting-started
  -
    title: About iocage
    path: about
  -
    title: iocage Library Essentials
    path: library-essentials
  -
    title: Command Line
    path: cli
  -
    title: Features
    path:  features
  -
    title: Migration
    path:  migration
  -
    title: Advanced Library Usage
    path: advanced

sass:
  style: compact
  sass_dir: css

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "handbook"
