title: iocage Handbook
email: authors@iocage.io

chapters:
  -
    title: Getting Started
    url: /getting-started/
  -
    title: About iocage
    url: /about/
  -
    title: iocage Library Essentials
    url: /library-essentials/
  -
    title: Command Line
    url: /cli/
  -
    title: Features
    url:  /features/
  -
    title: Migration
    url:  /migration/
  -
    title: Advanced Library Usage
    url: /advanced/

iocage_cli_tool: "ioc"

sass:
  style: compact
  sass_dir: css

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "handbook"
